config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  # resources :carts, only: [:create]
  post '/carts', to: 'carts#create'

  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  post '/cart/remove_item', to: 'carts#remove_item'
  post '/checkout', to: 'carts#checkout'
  get '/new_order', to: 'orders#create'

  # resources :stations, only: [:index]
  get '/stations', to: 'stations#index'

  # resources :trips, only: [:index, :show]
  get '/trips', to: 'trips#index'
  get '/trips/:id', to: 'trips#show', as: 'trip'

  # resources :users, only: [:new, :create, :edit, :update]
  get '/users/new', to: 'users#new', as: 'new_user'
  get 'users/:id', to: 'users#show', as: 'user'
  post '/users', to: 'users#create'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  # resources :orders, only: [:show, :update, :create]
  get '/orders/:id', to: 'orders#show', as: 'order'
  put '/orders/:id', to: 'orders#update'
  post '/orders', to: 'orders#create'

  # namespace :admin do
    # resources :stations, only: [:edit, :update, :new, :create, :destroy]
    get 'admin/stations/new', to: 'admin/stations#new', as: 'new_admin_station'
    post 'admin/stations', to: 'admin/stations#create'
    put 'admin/stations/:id', to: 'admin/stations#update'
    patch 'admin/stations/:id', to: 'admin/stations#update'
    get 'admin/stations/:id/edit', to: 'admin/stations#edit', as: 'edit_admin_station'
    delete 'admin/stations/:id', to: 'admin/stations#destroy', as: 'admin_station'

    # resources :dashboard, only: [:index]
    get 'admin/dashboard', to: 'admin/dashboard#index', as: 'admin_dashboard_index'

    # resources :trips, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/trips/new', to: 'admin/trips#new', as: 'new_admin_trip'
    post 'admin/trips', to: 'admin/trips#create'
    get 'admin/trips/:id/edit', to: 'admin/trips#edit', as: 'edit_admin_trip'
    patch 'admin/trips/:id', to: 'admin/trips#update'
    delete 'admin/trips/:id', to: 'admin/trips#destroy', as: 'admin_trip'

    # resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/conditions/new', to: 'admin/conditions#new', as: 'new_admin_condition'
    post 'admin/conditions', to: 'admin/conditions#create'
    get 'admin/conditions/:id/edit', to: 'admin/conditions#edit', as: 'edit_admin_condition'
    patch 'admin/conditions/:id', to: 'admin/conditions#update'
    delete 'admin/conditions/:id', to: 'admin/conditions#destroy', as: 'admin_condition'

    # resources :accessories, except: [:new]
    get 'admin/accessories/new', to: 'admin/accessories#new', as: 'admin_accessories_new'
    post 'admin/accessories', to: 'admin/accessories#create'
    get 'admin/accessories/:id/edit', to: 'admin/accessories#edit', as: 'edit_admin_accessory'
    put 'admin/accessories/:id', to: 'admin/accessories#update'
    patch 'admin/accessories/:id', to: 'admin/accessories#update'
    delete 'admin/accessories/:id', to: 'admin/accessories#destroy', as: 'admin_accessory'

    get 'admin/bike-shop/new', to: "admin/accessories#new" , as: 'admin_bike_shop_new'

    # resources :orders, only: [:show]
    get 'admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'

    get "admin/bike-shop", to: "admin/accessories#index"
  # end

  # resources :accessories, only: [:index, :show]
  get '/accessories', to: 'accessories#index'
  get '/accessories/:id', to: 'accessories#show', as: 'accessory'

  resources :conditions, only: [:index, :show]
  get '/conditions', to: 'conditions#index'
  get '/conditions/:id', to: 'conditions#show'


  get '/bike-shop', to: 'accessories#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/conditions-dashboard', to:'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/:id', to: 'stations#show', as: :station
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name
  validates_presence_of :dock_count
  validates_presence_of :city
  validates_presence_of :installation_date

  has_many :start_trips, class_name: 'Trip', foreign_key: 'start_station_id', dependent: :destroy
  has_many :end_trips, class_name: 'Trip', foreign_key: 'end_station_id', dependent: :destroy

  def to_param
    slug
  end

  def self.average_bikes
    average(:dock_count)
  end

  def self.most_bikes
    maximum(:dock_count)
  end

  def self.most_bikes_station
    find_by(dock_count: most_bikes)
  end

  def self.fewest_bikes
    minimum(:dock_count)
  end

  def self.fewest_bikes_station
    find_by(dock_count: fewest_bikes)
  end

  def self.newest
    find_by(installation_date: maximum(:installation_date))
  end

  def self.oldest
    find_by(installation_date: minimum(:installation_date))
  end

  def total_ride_starts
    start_trips.count
  end

  def total_ride_ends
    end_trips.count
  end

  def most_frequent_destination
    end_station = start_trips.select('trips.end_station_id, count (trips.end_station_id) AS total')
    .group('trips.end_station_id')
    .order('total DESC').first.end_station_id

    Station.find(end_station).name
  end

  def most_frequent_start
  start_station = end_trips.select('trips.start_station_id, count (trips.start_station_id) AS total')
    .group('trips.start_station_id')
    .order('total DESC').first.start_station_id

    Station.find(start_station).name
  end

  def date_with_most_trips
    start_trips.select('trips.start_date, count(trips.start_station_id) AS total')
    .group('trips.start_date')
    .order('total').first.start_date
  end

  def zip_code_with_most_trips
    start_trips.select('trips.zip_code, count(trips.id) AS total')
    .group('trips.zip_code')
    .order('total').last.zip_code
  end

  def bike_with_most_trips
    start_trips.select('trips.bike_id, count(trips.start_station_id) AS total')
    .group('trips.bike_id')
    .order('total').first.bike_id
  end

  def self.most_starting_rides
    joins(:start_trips).group("stations.id").order('COUNT(stations.id) DESC').first.name
  end

  def self.most_ending_rides
    joins(:end_trips).group("stations.id").order('COUNT(stations.id) DESC').first.name
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  before_action :set_station, only: [:edit, :update, :destroy]

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:success] = "#{@station.name} created!"
      redirect_to station_path(@station)
    else
      flash[:warning] = "All fields must be filled out"
      render :new
    end
  end

  def edit

  end

  def update
    @station.update(station_params)
    @station.slug = @station.name
    if @station.save
      flash[:success] = "#{@station.name} updated!"
      redirect_to station_path(@station)
    else
      flash[:warning] = "All fields must be filled out"
      render :edit
    end
  end

  def destroy
    name = set_station.name
    set_station.destroy
    
    flash[:success] = "#{name} Station deleted"
    redirect_to stations_path
  end

  private

  def set_station
    @station = Station.friendly.find(params[:id])
  end

  def station_params
    params.require(:station).permit(:name, :dock_count, :city, :installation_date, :slug)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show]

  def index
    @stations = Station.all
  end

  def show
    unless @station.start_trips.empty?
      @total_ride_starts = @station.total_ride_starts
      @total_ride_ends = @station.total_ride_ends
      @most_frequent_destination = @station.most_frequent_destination
      @most_frequent_start = @station.most_frequent_start
      @date_with_most_trips = @station.date_with_most_trips
      @zip_code_with_most_trips = @station.zip_code_with_most_trips
      @bike_with_most_trips = @station.bike_with_most_trips
    end
  end

  def dashboard
    @total = Station.count
    @average_bikes = Station.average_bikes
    @most_bikes = Station.most_bikes
    @most_bikes_station = Station.most_bikes_station.name
    @fewest_bikes = Station.fewest_bikes
    @fewest_bikes_station = Station.fewest_bikes_station.name
    @newest = Station.newest.name
    @oldest = Station.oldest.name
  end

  private

  def set_station
    @station = Station.friendly.find(params[:id])
  end
end

app/views/stations/dashboard.html.erb
<h2> Stations Dashboard</h2>

<div class="row">
  <div class="col-sm-6">
  <h3>Station information</h3>
  <p class="important-text"><strong>Total Stations: <%= @total %></strong></p>
  <p class="hidden"><%= @total %></p>
  <p>
    <% @total.times do %>
      <i class="fas fa-building dashboard-icon"></i>
    <% end %>

  </p>

  <p class="important-text"><strong>Newest station:</strong></p>
  <p><%= @newest %></p>

  <p class="important-text"><strong>Oldest station:</strong></p>
  <p><%= @oldest %> </p>
  </div>
  <div class="col-sm-6">
    <h3>Station bike information</h3>
      <p class="important-text"><strong>Average Bikes Per Station: <%= @average_bikes.to_i %></strong></p>
      <p class="bike-holder">
          <% @average_bikes.to_i.times do %>
            <i class="fas fa-bicycle"></i>
          <% end %>

      </p>
      <p class="important-text"><strong><%= @most_bikes_station %> has the most bikes: <%= @most_bikes %></strong></p>

      <p class="bike-holder">
      <% @most_bikes.times do %>
        <i class="fas fa-bicycle"></i>
      <% end %>
      </p>
      <p class="important-text"><strong><%= @fewest_bikes_station %> has the fewest bikes: <%= @fewest_bikes%> </strong></p>

      <p class="bike-holder">
      <% @fewest_bikes.times do %>
        <i class="fas fa-bicycle"></i>
      <% end %>
      </p>
    </div>
</div>

app/views/stations/index.html.erb
<h1> Stations</h1>


<% if current_admin? %>
  <%= link_to new_admin_station_path do %>
    <h4><i class="fas fa-building dashboard-icon"></i>Create station</h4>
  <% end %>
<% end %>

<div class="row table-heading">
  <div class="col-sm-1">
  </div>
  <div class="col-sm-4">
    <p>Name<p>
  </div>
  <div class="col-sm-2">
    <p>Dock count<p>
  </div>
  <div class="col-sm-2">
    <p>City<p>
  </div>
  <div class="col-sm-3">
    <p>Installation date<p>
  </div>
</div>

<div class="index-container">
<% @stations.each do |station| %>
<section class="section-index-container" id=<%= "display_#{station.id}" %>>
  <div class="row station-row">
    <div class="col-sm-1 icon-column">
      <% if current_user&.admin? %>
      <%= link_to edit_admin_station_path(station), method: :get do %>
      <i class="far fa-edit"></i>
      <p class="hidden">Edit</p>
      <% end %>
        <%= link_to admin_station_path(station), method:"delete", data: {confirm: "Are you sure you want to delete #{station.name} Station?"} do %>
          <i class="far fa-trash-alt"></i>
          <p class="hidden">Delete</p>
        <% end %>
      <% end %>
        <%= link_to station_path(station) do %>
          <i class="fas fa-info-circle"></i>
          <p class="hidden">Info</p>
        <% end %>
    </div>
      <div class="col-sm-4">
        <p><%= station.name %></p>
    </div>
    <div class="col-sm-2">
      <p><%= station.dock_count %></p>
    </div>
    <div class="col-sm-2">
      <p><%= station.city %></p>
    </div>
    <div class="col-sm-3">
      <p><%= station.installation_date.to_s.chomp("00:00:00 UTC") %></p>
    </div>
  </div>
  </section>
<% end %>
</div>

app/views/stations/show.html.erb
<h2><%= @station.name %>

<% if current_admin? %>
    <%= link_to edit_admin_station_path(@station) do %>
        <i class="far fa-edit link-text">
        <p class="hidden">Edit</p></i>
    <% end %>

    <%= link_to admin_station_path(@station), method: :delete, data: {confirm: "Are you sure you want to delete #{@station.name} Station?"} do %>
      <i class="far fa-trash-alt"></i>
      <p class="hidden">Delete</p>
    <% end %>

<% end %>
</h2>

<div class="row">
  <div class="col-sm-6">
    <h3>Station information</h3>
    <p class="important-text"><strong>City:</strong></p>
    <p><%= @station.city %></p>
    <p class="important-text"><strong>Dock count: <%= @station.dock_count %></strong><p>
    <p class="bike-holder">
      <% @station.dock_count.times do %>
        <i class="fas fa-bicycle"></i>
      <% end %>
    </p>
    <p class="important-text"><strong>Installation date:</strong><p>
    <p><%= @station.installation_date.to_s %></p>
  </div>
  <div class="col-sm-6">
    <h3>Trip information</h3>
    <% unless @station.start_trips.empty? %>
      <p class="important-text"><strong>Number of rides started at this station:</strong></p>
      <p><%= @total_ride_starts %></p>
      <p class="important-text"><strong>Number of rides ended at this station:</strong></p>
      <p><%= @total_ride_ends %></p>
      <p class="important-text"><strong>Most frequent destination station:</strong></p>
      <p><%= @most_frequent_destination %></p>
      <p class="important-text"><strong>Most frequent origination station:</strong></p>
      <p><%= @most_frequent_start %></p>
      <p class="important-text"><strong>Date with the highest number of trips:</strong></p>
      <p><%= @date_with_most_trips %></p>
      <p class="important-text"><strong>Most frequent zip code for users starting trips at this station:</strong></p>
      <p><%= @zip_code_with_most_trips %></p>
      <p class="important-text"><strong>Bike with most trips:</strong></p>
      <p><%= @bike_with_most_trips %> </p>
    <% end %>
  </div>
</div>