config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  # resources :carts, only: [:create]
  post '/carts', to: 'carts#create'

  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  post '/cart/remove_item', to: 'carts#remove_item'
  post '/checkout', to: 'carts#checkout'
  get '/new_order', to: 'orders#create'

  # resources :stations, only: [:index]
  get '/stations', to: 'stations#index'

  # resources :trips, only: [:index, :show]
  get '/trips', to: 'trips#index'
  get '/trips/:id', to: 'trips#show', as: 'trip'

  # resources :users, only: [:new, :create, :edit, :update]
  get '/users/new', to: 'users#new', as: 'new_user'
  get 'users/:id', to: 'users#show', as: 'user'
  post '/users', to: 'users#create'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  # resources :orders, only: [:show, :update, :create]
  get '/orders/:id', to: 'orders#show', as: 'order'
  put '/orders/:id', to: 'orders#update'
  post '/orders', to: 'orders#create'

  # namespace :admin do
    # resources :stations, only: [:edit, :update, :new, :create, :destroy]
    get 'admin/stations/new', to: 'admin/stations#new', as: 'new_admin_station'
    post 'admin/stations', to: 'admin/stations#create'
    put 'admin/stations/:id', to: 'admin/stations#update'
    patch 'admin/stations/:id', to: 'admin/stations#update'
    get 'admin/stations/:id/edit', to: 'admin/stations#edit', as: 'edit_admin_station'
    delete 'admin/stations/:id', to: 'admin/stations#destroy', as: 'admin_station'

    # resources :dashboard, only: [:index]
    get 'admin/dashboard', to: 'admin/dashboard#index', as: 'admin_dashboard_index'

    # resources :trips, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/trips/new', to: 'admin/trips#new', as: 'new_admin_trip'
    post 'admin/trips', to: 'admin/trips#create'
    get 'admin/trips/:id/edit', to: 'admin/trips#edit', as: 'edit_admin_trip'
    patch 'admin/trips/:id', to: 'admin/trips#update'
    delete 'admin/trips/:id', to: 'admin/trips#destroy', as: 'admin_trip'

    # resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/conditions/new', to: 'admin/conditions#new', as: 'new_admin_condition'
    post 'admin/conditions', to: 'admin/conditions#create'
    get 'admin/conditions/:id/edit', to: 'admin/conditions#edit', as: 'edit_admin_condition'
    patch 'admin/conditions/:id', to: 'admin/conditions#update'
    delete 'admin/conditions/:id', to: 'admin/conditions#destroy', as: 'admin_condition'

    # resources :accessories, except: [:new]
    get 'admin/accessories/new', to: 'admin/accessories#new', as: 'admin_accessories_new'
    post 'admin/accessories', to: 'admin/accessories#create'
    get 'admin/accessories/:id/edit', to: 'admin/accessories#edit', as: 'edit_admin_accessory'
    put 'admin/accessories/:id', to: 'admin/accessories#update'
    patch 'admin/accessories/:id', to: 'admin/accessories#update'
    delete 'admin/accessories/:id', to: 'admin/accessories#destroy', as: 'admin_accessory'

    get 'admin/bike-shop/new', to: "admin/accessories#new" , as: 'admin_bike_shop_new'

    # resources :orders, only: [:show]
    get 'admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'

    get "admin/bike-shop", to: "admin/accessories#index"
  # end

  # resources :accessories, only: [:index, :show]
  get '/accessories', to: 'accessories#index'
  get '/accessories/:id', to: 'accessories#show', as: 'accessory'

  resources :conditions, only: [:index, :show]
  get '/conditions', to: 'conditions#index'
  get '/conditions/:id', to: 'conditions#show'


  get '/bike-shop', to: 'accessories#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/conditions-dashboard', to:'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/:id', to: 'stations#show', as: :station
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
    if(params[:status])
      @orders = Order.where(status: params[:status])
    else
      @orders = Order.all
    end
    @order_by_status = Order.group_by_status
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorized?

  def index
    @orders = current_user.orders
  end
end

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h2>Profile for <%= current_user.username %>

    <% if current_user&.admin? %>
        <%= link_to edit_user_path(current_user) do %>
            <i class="far fa-edit link-text admin-edit">
            <p class="hidden">Edit</p></i>
        <% end %>
    <% end %>
  </h2>

<div class="row">
  <div class="col-sm-4">
    <p class="important-text"><strong>First name:</strong></p>
    <p><%= current_user.first_name %></p>

    <p class="important-text"><strong>Last name:</strong></p>
    <p><%= current_user.last_name %></p>


  </div>
  <div class="col-sm-8">
    <p class="important-text"><strong>Address:</strong></p>
    <p><%= current_user.address %>, <%= current_user.city %></p>
    <p><%= current_user.state %>, <%= current_user.zip_code %></p>

  </div>
</div>


  </div>
  <div class="col-sm-6">
    <h2>Creation options</h2>
    <%= link_to new_admin_condition_path do %>
      <h4><i class="fas fa-sun dashboard-icon"></i>Condition</h4>
    <% end %>
    <%= link_to new_admin_trip_path do %>
      <h4><i class="fas fa-map-marked-alt dashboard-icon"></i>Trip</h4>
    <% end %>
    <%= link_to new_admin_station_path do %>
      <h4><i class="fas fa-building dashboard-icon"></i>Station</h4>
    <% end %>
    <%= link_to admin_bike_shop_new_path do %>
      <h4><i class="fas fa-box-open dashboard-icon"></i>Accessory</h4><%= link_to "View Accessories", admin_bike_shop_path %>
    <% end %>
  </div>
</div>


<h3>All user orders:</h3>

<section class="dashboard-filter-options">
  <p><i class="fas fa-filter"></i></p>
  <%= link_to "All", admin_dashboard_index_path, class:"hvr-skew" %>
  <p class="divider"> | </p>
  <%= link_to "Ordered (#{@order_by_status["ordered"]})", admin_dashboard_index_path(status: "ordered"), class:"hvr-skew" %>
  <p class="divider"> | </p>
  <%= link_to "Paid (#{@order_by_status["paid"]})", admin_dashboard_index_path(status: "paid"), class:"hvr-skew" %>
  <p class="divider"> | </p>
  <%= link_to "Cancelled (#{@order_by_status["cancelled"]})", admin_dashboard_index_path(status: "cancelled"), class:"hvr-skew" %>
  <p class="divider"> | </p>
  <%= link_to "Completed (#{@order_by_status["completed"]})", admin_dashboard_index_path(status: "completed"), class:"hvr-skew" %>
</section>

<h3 class="dashboard-heading"></h3>

<div class="row table-heading">
  <div class="col-sm-1">

  </div>
  <div class="col-sm-1">
    <p>ID</p>
  </div>
  <div class="col-sm-2">
    <p>Name</p>
  </div>
  <div class="col-sm-2">
    <p>Created at</p>
  </div>
  <div class="col-sm-2">
    <p>Status</p>
  </div>
  <div class="col-sm-2">
    <p>Change status</p>
  </div>
</div>

<div class="index-container trips-container">
  <% @orders.each do |order| %>
  <section id=<%= "display_#{order.id}" %> class="section-index-container">
    <div class="row station-row">
      <div class="col-sm-1 icon-column">
        <%= link_to admin_order_path(order) do %>
          <i class="fas fa-info-circle"></i>
          <p class="hidden">Info</p>
        <% end %>
      </div>
      <div class="col-sm-1">
        <p><%= order.id %></p>
      </div>
      <div class="col-sm-2">
        <p><%= order.user.full_name %></p>
      </div>
      <div class="col-sm-2">
        <p><%= order.created_at %></p>
      </div>
      <div class="col-sm-2">
        <p><%= order.status %></p>
      </div>
      <div class="col-sm-4">
        <% if order.status == "ordered" %>
          <%= link_to "mark as paid", order_path(order, new_status: "paid"), method: :put, class:"btn btn-primary reset-button-style" %>
          <%= link_to "cancel", order_path(order, new_status: "cancelled"), method: :put, class:"btn btn-primary cancel-button-style" %>
        <% elsif order.status == "paid" %>
          <%= link_to "mark as completed", order_path(order, new_status: "completed"), method: :put, class:"btn btn-primary reset-button-style" %>
          <%= link_to "cancel", order_path(order, new_status: "cancelled"), method: :put, class:"btn btn-primary cancel-button-style" %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>
</div>