config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  # resources :carts, only: [:create]
  post '/carts', to: 'carts#create'

  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  post '/cart/remove_item', to: 'carts#remove_item'
  post '/checkout', to: 'carts#checkout'
  get '/new_order', to: 'orders#create'

  # resources :stations, only: [:index]
  get '/stations', to: 'stations#index'

  # resources :trips, only: [:index, :show]
  get '/trips', to: 'trips#index'
  get '/trips/:id', to: 'trips#show', as: 'trip'

  # resources :users, only: [:new, :create, :edit, :update]
  get '/users/new', to: 'users#new', as: 'new_user'
  get 'users/:id', to: 'users#show', as: 'user'
  post '/users', to: 'users#create'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  # resources :orders, only: [:show, :update, :create]
  get '/orders/:id', to: 'orders#show', as: 'order'
  put '/orders/:id', to: 'orders#update'
  post '/orders', to: 'orders#create'

  # namespace :admin do
    # resources :stations, only: [:edit, :update, :new, :create, :destroy]
    get 'admin/stations/new', to: 'admin/stations#new', as: 'new_admin_station'
    post 'admin/stations', to: 'admin/stations#create'
    put 'admin/stations/:id', to: 'admin/stations#update'
    patch 'admin/stations/:id', to: 'admin/stations#update'
    get 'admin/stations/:id/edit', to: 'admin/stations#edit', as: 'edit_admin_station'
    delete 'admin/stations/:id', to: 'admin/stations#destroy', as: 'admin_station'

    # resources :dashboard, only: [:index]
    get 'admin/dashboard', to: 'admin/dashboard#index', as: 'admin_dashboard_index'

    # resources :trips, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/trips/new', to: 'admin/trips#new', as: 'new_admin_trip'
    post 'admin/trips', to: 'admin/trips#create'
    get 'admin/trips/:id/edit', to: 'admin/trips#edit', as: 'edit_admin_trip'
    patch 'admin/trips/:id', to: 'admin/trips#update'
    delete 'admin/trips/:id', to: 'admin/trips#destroy', as: 'admin_trip'

    # resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/conditions/new', to: 'admin/conditions#new', as: 'new_admin_condition'
    post 'admin/conditions', to: 'admin/conditions#create'
    get 'admin/conditions/:id/edit', to: 'admin/conditions#edit', as: 'edit_admin_condition'
    patch 'admin/conditions/:id', to: 'admin/conditions#update'
    delete 'admin/conditions/:id', to: 'admin/conditions#destroy', as: 'admin_condition'

    # resources :accessories, except: [:new]
    get 'admin/accessories/new', to: 'admin/accessories#new', as: 'admin_accessories_new'
    post 'admin/accessories', to: 'admin/accessories#create'
    get 'admin/accessories/:id/edit', to: 'admin/accessories#edit', as: 'edit_admin_accessory'
    put 'admin/accessories/:id', to: 'admin/accessories#update'
    patch 'admin/accessories/:id', to: 'admin/accessories#update'
    delete 'admin/accessories/:id', to: 'admin/accessories#destroy', as: 'admin_accessory'

    get 'admin/bike-shop/new', to: "admin/accessories#new" , as: 'admin_bike_shop_new'

    # resources :orders, only: [:show]
    get 'admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'

    get "admin/bike-shop", to: "admin/accessories#index"
  # end

  # resources :accessories, only: [:index, :show]
  get '/accessories', to: 'accessories#index'
  get '/accessories/:id', to: 'accessories#show', as: 'accessory'

  resources :conditions, only: [:index, :show]
  get '/conditions', to: 'conditions#index'
  get '/conditions/:id', to: 'conditions#show'


  get '/bike-shop', to: 'accessories#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/conditions-dashboard', to:'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/:id', to: 'stations#show', as: :station
end

app/views/partials/_anonymousnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-color">

  <a class="navbar-brand hvr-skew" href="/"><i class="fas fa-bicycle"></i>SHARE</a>
  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon navbar-"></span>
  </button>
  <p class="nav-link"> | </p>
  <a class="navbar-brand hvr-skew shop-icon" href="/bike-shop"></i>SHOP</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to cart_path, class:"nav-link hvr-skew", method: :get do %>
          <p><i class="fas fa-shopping-cart"></i><% if @cart.total_count > 0 %>Items in cart: <%= @cart.total_count %><% end %></p>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to "Stations", stations_path, class:"nav-link hvr-skew" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Trips", trips_path, class:"nav-link hvr-skew" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Conditions", conditions_path, class:"nav-link hvr-skew" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Account", new_user_path, class:"nav-link hvr-skew" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Login", login_path, class:"nav-link hvr-skew" %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/_footer.html.erb
<footer>
  Created by Keegan, Seth, and Connor
</footer>

app/views/partials/_station_form.html.erb
<div class="all-forms">
  <%= form_for [:admin, @station] do |f| %>
    <%= f.label :name %>
    <div class="form-group">
      <%= f.text_field :name %>
    </div>
      <%= f.label :dock_count %>
    <div class="form-group">
      <%= f.number_field :dock_count %>
    </div>
    <%= f.label :city %>
    <div class="form-group">
      <%= f.text_field :city %>
    </div>
    <%= f.label :installation_date %>
    <div class="form-group">
      <%= f.date_field :installation_date %>
    </div>
    <section class="main-button create-account">
      <a>
        <%= f.submit class:"text reset-button" %>
        <span class="line -right"></span>
        <span class="line -top"></span>
        <span class="line -left"></span>
        <span class="line -bottom"></span>
      </a>
  </section>
  <% end %>
</div>

app/views/partials/_trip_form.html.erb
<div class="all-forms">
<%= form_for [:admin, @trip] do |f| %>

  <%= f.label :duration %>
  <div class="form-group">
    <%= f.number_field :duration %>
  </div>

  <%= f.label :start_date %>
  <div class="form-group">
    <%= f.date_field :start_date %>
  </div>

  <%= f.label :start_station %>
  <div class="form-group">
    <%= f.collection_select :start_station_id, Station.order(:name), :id, :name %>
  </div>

  <%= f.label :end_date %>
  <div class="form-group">
    <%= f.date_field :end_date %>
  </div>

  <%= f.label :end_station %>
  <div class="form-group">
    <%= f.collection_select :end_station_id, Station.order(:name), :id, :name %>
  </div>

  <%= f.label :subscription_type %>
  <div class="form-group">
    <%= f.select :subscription_type, ['Customer', 'Subscriber'], include_blank: true %>
  </div>

  <%= f.label :zip_code %>
  <div class="form-group">
    <%= f.number_field :zip_code %>
  </div>

  <%= f.label :bike_id %>
  <div class="form-group">
    <%= f.number_field :bike_id %>
  </div>

  <section class="main-button create-account">
    <a>
      <%= f.submit class:"text reset-button" %>
      <span class="line -right"></span>
      <span class="line -top"></span>
      <span class="line -left"></span>
      <span class="line -bottom"></span>
    </a>
  </section>
<% end %>
</div>

app/views/partials/_user_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-color">

  <a class="navbar-brand hvr-skew" href="/"><i class="fas fa-bicycle"></i>SHARE</a>
  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon navbar-"></span>
  </button>
  <p class="nav-link"> | </p>
  <a class="navbar-brand hvr-skew shop-icon" href="/bike-shop"></i>SHOP</a>
  <% if !current_admin? %>
    <%= link_to dashboard_path do %>
      <p class="dark-text"> Logged in as <%= current_user.first_name %></p>
    <% end %>
  <%elsif current_admin? %>
    <%= link_to admin_dashboard_index_path do %>
      <p class="dark-text"> Logged in as admin: <%= current_user.first_name %></p>
    <% end %>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to cart_path, class:"nav-link hvr-skew link", method: :get do %>
        <p><i class="fas fa-shopping-cart"></i><% if @cart.total_count > 0 %>Items in cart: <%= @cart.total_count %><% end %></p>
        <% end %>
      </li>
      <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Dashboards
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to "Stations", stations_dashboard_path, class: "link" %>
         <div class="dropdown-divider"></div>
         <%= link_to "Trips", trips_dashboard_path, class: "link" %>
         <div class="dropdown-divider"></div>
         <%= link_to "Conditions", conditions_dashboard_path, class: "link" %>
       </div>
     </li>
      <li class="nav-item active">
        <section id="jfc">
        <%= link_to "Stations", stations_path, class:"nav-link hvr-skew link" %>
        </section>
      </li>
      <li class="nav-item active">
        <%= link_to "Trips", trips_path, class:"nav-link hvr-skew link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Conditions", conditions_path, class:"nav-link hvr-skew link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", logout_path, class:"nav-link hvr-skew link" %>
      </li>
    </ul>
  </div>
</nav>