config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  # resources :carts, only: [:create]
  post '/carts', to: 'carts#create'

  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  post '/cart/remove_item', to: 'carts#remove_item'
  post '/checkout', to: 'carts#checkout'
  get '/new_order', to: 'orders#create'

  # resources :stations, only: [:index]
  get '/stations', to: 'stations#index'

  # resources :trips, only: [:index, :show]
  get '/trips', to: 'trips#index'
  get '/trips/:id', to: 'trips#show', as: 'trip'

  # resources :users, only: [:new, :create, :edit, :update]
  get '/users/new', to: 'users#new', as: 'new_user'
  get 'users/:id', to: 'users#show', as: 'user'
  post '/users', to: 'users#create'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'

  # resources :orders, only: [:show, :update, :create]
  get '/orders/:id', to: 'orders#show', as: 'order'
  put '/orders/:id', to: 'orders#update'
  post '/orders', to: 'orders#create'

  # namespace :admin do
    # resources :stations, only: [:edit, :update, :new, :create, :destroy]
    get 'admin/stations/new', to: 'admin/stations#new', as: 'new_admin_station'
    post 'admin/stations', to: 'admin/stations#create'
    put 'admin/stations/:id', to: 'admin/stations#update'
    patch 'admin/stations/:id', to: 'admin/stations#update'
    get 'admin/stations/:id/edit', to: 'admin/stations#edit', as: 'edit_admin_station'
    delete 'admin/stations/:id', to: 'admin/stations#destroy', as: 'admin_station'

    # resources :dashboard, only: [:index]
    get 'admin/dashboard', to: 'admin/dashboard#index', as: 'admin_dashboard_index'

    # resources :trips, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/trips/new', to: 'admin/trips#new', as: 'new_admin_trip'
    post 'admin/trips', to: 'admin/trips#create'
    get 'admin/trips/:id/edit', to: 'admin/trips#edit', as: 'edit_admin_trip'
    patch 'admin/trips/:id', to: 'admin/trips#update'
    delete 'admin/trips/:id', to: 'admin/trips#destroy', as: 'admin_trip'

    # resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    get 'admin/conditions/new', to: 'admin/conditions#new', as: 'new_admin_condition'
    post 'admin/conditions', to: 'admin/conditions#create'
    get 'admin/conditions/:id/edit', to: 'admin/conditions#edit', as: 'edit_admin_condition'
    patch 'admin/conditions/:id', to: 'admin/conditions#update'
    delete 'admin/conditions/:id', to: 'admin/conditions#destroy', as: 'admin_condition'

    # resources :accessories, except: [:new]
    get 'admin/accessories/new', to: 'admin/accessories#new', as: 'admin_accessories_new'
    post 'admin/accessories', to: 'admin/accessories#create'
    get 'admin/accessories/:id/edit', to: 'admin/accessories#edit', as: 'edit_admin_accessory'
    put 'admin/accessories/:id', to: 'admin/accessories#update'
    patch 'admin/accessories/:id', to: 'admin/accessories#update'
    delete 'admin/accessories/:id', to: 'admin/accessories#destroy', as: 'admin_accessory'

    get 'admin/bike-shop/new', to: "admin/accessories#new" , as: 'admin_bike_shop_new'

    # resources :orders, only: [:show]
    get 'admin/orders/:id', to: 'admin/orders#show', as: 'admin_order'

    get "admin/bike-shop", to: "admin/accessories#index"
  # end

  # resources :accessories, only: [:index, :show]
  get '/accessories', to: 'accessories#index'
  get '/accessories/:id', to: 'accessories#show', as: 'accessory'

  resources :conditions, only: [:index, :show]
  get '/conditions', to: 'conditions#index'
  get '/conditions/:id', to: 'conditions#show'


  get '/bike-shop', to: 'accessories#index'
  get '/dashboard', to: 'dashboard#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/conditions-dashboard', to:'conditions#dashboard'
  get '/stations-dashboard', to: 'stations#dashboard'
  get '/trips-dashboard', to: 'trips#dashboard'
  get '/:id', to: 'stations#show', as: :station
end

app/models/cart.rb
class Cart
  attr_reader :contents, :last_removed, :last_removed_name

  def initialize(content)
    @contents = content || Hash.new(0)
    @last_removed = @contents["last_removed"].to_i
    @last_removed_name = @contents["last_removed_name"]
    @contents.delete("last_removed")
    @contents.delete("last_removed_name")
  end

  def total_count
    @contents.values.sum
  end

  def add_accessory(accessory_id)
    @contents[accessory_id.to_s] ||= 0
    @contents[accessory_id.to_s] += 1
  end

  def update_totals(totals)
    totals.keys.each do |key|
      if key.to_i.to_s == key
        contents[key] = totals[key].to_i
      end
    end
  end

  def subtotal(accessory)
    accessory.price * @contents[accessory.id.to_s]
  end

  def total(accessories)
    accessories.inject(0) {|sum, accessory| sum += subtotal(accessory)}
  end

  def accessories
    @contents.keys.map do |key|
      key.to_i
    end
  end

  def remove_accessory(id)
    contents.delete(id)
  end

  def clear
    contents.clear
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_action :update, only: [:remove_item]

  def create
    accessory = Accessory.find(params[:accessory_id])
    @cart = Cart.new(session[:cart])
    @cart.add_accessory(accessory.id)
    session[:cart] = @cart.contents
    quantity = @cart.contents[accessory.id.to_s]

    if params[:path] == 'show'
      flash[:notice] = "#{quantity} #{accessory.name} in your cart"
      redirect_to accessory_path(accessory)
    elsif params[:path] == 'index'
      flash[:notice] = "#{quantity} #{accessory.name} in your cart"
      redirect_to accessories_path
    elsif params[:path] == 'checkout'
      redirect_to root_path
    end
  end

  def show
    @accessories = Accessory.where(id: @cart.accessories)
  end

  def update
    new_totals = {}
    params.keys.each do |key|
      if key.to_s.include?("accessory_")
        id = key.to_s[-1]
        new_totals[id] = params[key]
      end
    end
    @cart.update_totals(new_totals)
  end

  def remove_item
    id = params["accessory_id"]
    accessory = Accessory.find(id.to_i)
    name = accessory.name
    @cart.remove_accessory(id)
    session[:cart][:last_removed] = id
    session[:cart][:last_removed_name] = name
    flash[:cart_remove] = "Successfully removed #{view_context.link_to name, accessory_path(accessory)}"

    redirect_to cart_path
  end
end

app/views/carts/show.html.erb
<head>
  <script>
    var accessories = {};
    <% @accessories.each do |accessory| %>
      accessories[<%= accessory.id %>] = {};
      accessories[<%= accessory.id %>].quantity = <%= @cart.contents[accessory.id.to_s] %>
      accessories[<%= accessory.id %>].price = <%= accessory.price %>
    <% end %>
    var lastRemoved = <%= @cart.last_removed %>
    var lastRemovedName = "<%= @cart.last_removed_name %>"
  </script>
  <%= javascript_include_tag "cart" %>
</head>

<body onload="display_quantity(); checkFlash();" onclick="update();">

<div class="row">
  <div class="col-sm-8">
    <h2> Your cart: </h2>
  </div>
  <div class="col-sm-4">
    <h2>Payment:</h2>
  </div>
</div>



<div class="row">
  <div class="col-sm-8">
    <div class="row row-align-center">
<% @accessories.each do |accessory| %>
  <div class="col-sm-5">
    <div class="container text-muted">
      <div class="card">
        <div class="card-body card-reset">
          <p id=<%= "display_#{accessory.id}" %>>
            <%= image_tag(accessory.image_url, size: "100x100") %>
            <p>name: <%= accessory.name %></p>
            <p>price: <%= number_to_currency(accessory.price) %></p>
            <p>quantity:</p>
            <button onclick=<%= "decrement(#{accessory.id});" %>>-</button>
            <nobr id=<%= "#{accessory.id}_quantity" %>></nobr>
            <button onclick=<%= "increment(#{accessory.id});" %>>+</button>
            <h4>Subtotal:</h4>
            <span>$</span><nobr id=<%= "#{accessory.id}_subtotal" %>></nobr>
            <nobr id=<%= "remove_#{accessory.id}" %> >
              <%= link_to "Remove", cart_remove_item_path(accessory_id: "#{accessory.id}"), method: :post %>
            </nobr>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>
  </div>
  </div>
  <div class="col-4">
    <h3>Total: $<nobr id="total"></nobr></h3>
    <p class="credit-card-logos"><i class="fab fa-cc-visa"></i>    <i class="fab fa-cc-amex"></i>    <i class="fab fa-cc-paypal"></i>    <i class="fab fa-cc-apple-pay"></i></p>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <br>
      <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

      <% if @cart.total(@accessories) > 0 %>
        <% if current_user && @cart.total(@accessories) > 0 %>
          <span><%= link_to "Checkout", orders_path, method: :post, class:"btn btn-primary btn-lg" %>
        <% else %>
          <span><%= link_to "Checkout", login_path, method: :post, class:"btn btn-primary btn-lg" %>
        <% end %>
      <% end %>
  </div>
</div>

<form id="exit_values" action="/cart" method="post">
  <% @accessories.each do |accessory| %>
    <input type="hidden" id=<%= "update_accessory_#{accessory.id}" %> name=<%= "accessory_#{accessory.id}" %> value="" />
  <% end %>
</form>

</body>